application: flyercu
version: 1
runtime: python
api_version: 1

handlers:
- url: /tasks/.*
  script: admin.py
  login: admin

- url: /static
  static_dir: static

- url: /callback
  script: WIND_auth.py

- url: /.*
  script: flyer.py
