application: flyercu
version: 2
runtime: python
api_version: 1

handlers:
- url: /tasks/.*
  script: admin.py
  login: admin

- url: /static
  static_dir: static

- url: /auth/.*
  script: auth.py

- url: /_ah/mail/support@.*\.appspotmail\.com 
  script: handle_support.py
  login: admin

- url: /.*
  script: flyer.py

inbound_services:
- mail